config/routes.rb
Foo::Application.routes.draw do
  resources :accounts

  match ':controller(/:action(/:id))(.:format)'
  match 'accoounts/logout' => 'accounts#logout'
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :email, :password

  validates :email, :presence => true, 
                    :uniqueness => true 
  validates :password, :presence => true, 
                       :length => {:minimum => 4}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :auth_user, :only => [:index, :login, :new, :create]
  before_filter :not_auth_user, :except => [:index, :login, :new, :create]
  before_filter :different_user, :except => [:index, :login, :new, :create, :show]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
    @account = Account.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @account }
    end
  end

  def login
    @account = Account.find_by_email(params[:account][:email])
    if @account && @account.password == params[:account][:password]
      session[:account_id] = @account.id
      redirect_to @account, notice: 'login success'
      return
    end

    @account = Account.new(params[:account])
    @account.valid?(:save)
    respond_to do |format|
      format.html { render action: "index" }
      format.json { render json: @account.errors, status: :unprocessable_entity }
    end

  end

  def logout
    session[:account_id] = nil
    redirect_to(:controller => "accounts", :action => "index")
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find_by_id(params[:id])

    if @account
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @account }
      end
    else
      @account = Account.find_by_id(session[:account_id])
      redirect_to @account
      return
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        session[:account_id] = @account.id
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      session[:account_id] = nil
      format.html { redirect_to accounts_url, notice: 'delete yr account.' }
      format.json { head :no_content }
    end
  end

  def auth_user
    redirect_to(:controller => 'accounts', :action => session[:account_id]) if session[:account_id] != nil
  end

  def not_auth_user
    redirect_to(:controller => 'accounts', :action => 'index') if session[:account_id] == nil
  end

  def different_user 
    if session[:account_id] != params[:id]
      params[:id] = session[:account_id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="container">

  <div class="header">
    <div class="hero-unit">
      <h1>Login to your account</h1><br />
      <p>welcome to my page</p>
    </div>
  </div>

  <div class="row">

    <div class="span6">


      <%= form_for @account, :url => {:action => 'login'}, :html => { :class => 'form-horizontal'} do |f| %>

        <% if @account.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

            <ul>
              <% @account.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <p id="notice"><%= notice %></p>


        <div class="control-group">
          <label class="control-label" for="createEmail">email</label>
          <div class="controls">
            <%= f.text_field(:email, {:class => 'span3', :placeholder => "email"}) %>  
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="createEmail">password</label>
          <div class="controls">
            <%= f.password_field(:password, {:class => 'span3', :placeholder => "password"}) %>
          </div>
        </div>
        <div class="control-group">

          <label class="control-label"></label>
          <div class="controls">

            <%= f.submit "Login", :class => 'btn' %>
          </div>
        </div> 
      <% end %>
    </div>

    <div class="span6">
      <%= link_to 'New Account', new_account_path %>
    </div>

  </div>

</div>

app/views/accounts/new.html.erb
<div class="container">

  <div class="header">
    <div class="hero-unit">
      <h1>create a new account</h1><br />
      <p>welcome to my page</p>
    </div>
  </div>


  <div class="row">

    <div class="span6">

      <%= form_for (@account), :url => {:action => 'create'}, :html => {:class => 'form-horizontal'} do |f| %>
        <% if @account.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

            <ul>
              <% @account.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="control-group">

          <label class="control-label" for="createEmail">email</label>
          <div class="controls">
            <%= f.text_field(:email, {:class => 'span3', :id => 'createEmail', :placeholder => 'email'}) %>
          </div>

        </div>

        <div class="control-group">

          <label class="control-label" for="createPassword">password</label>
          <div class="controls">
            <%= f.password_field(:password, {:class => 'span3', :id => 'createPassword', :placeholder => 'password'}) %>
          </div>

        </div>

        <div class="control-group">

          <label class="control-label"></label>
          <div class="controls">
            <%= f.submit({:class => 'btn'}) %>
          </div>

        </div>

      <% end %>

      <%= link_to 'Back', accounts_path %>

    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Delete', account_path(@account), :method => :delete %> |
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Logout', :action => 'logout' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>